### ISSUE TITLE
[Package Request] Franka Emika packages

### ISSUE THREAD

**Issue by liborw** [ros-noetic-arch/ros-noetic-desktop-full#11]
Please add Franka Emika packages, I will add the PKGBUILDs, thanks.

https://github.com/frankaemika/libfranka:
 - [x] ros-noetic-libfranka

https://github.com/frankaemika/franka_ros: 
 - [x] ros-noetic-franka-ros (split package) (repo has been created)

https://github.com/ros-planning/panda_moveit_config:
 - [x] ros-noetic-panda-moveit-config (repo has been created)

**Comment by acxz** [comment]
@liborw thx for the package request, for `ros-noetic-franka-ros` you will have to list the packages needed for it as well, such as dependencies that are not packaged. Makes it easier for me to track and create the repos.

**Comment by liborw** [comment]
@acxz do you mean dependencies that are not already in ros-noetic-arch or pacman repositories, these are only the `libfranka` and `panda-moveit-config`.

**Comment by acxz** [comment]
I meant the individual packages of the metapackage, but after seeing you PR. It is clear.

**Comment by acxz** [comment]
packages created and synced!
