### ISSUE TITLE
[Package Request] ros-noetic-joint-trajectory-controller

### ISSUE THREAD

**Issue by liborw** [ros-noetic-arch/ros-noetic-desktop-full#12]
[joint_trajectory_controller](http://wiki.ros.org/joint_trajectory_controller?distro=noetic):
 - [x] ros-noetic-joint-trajectory-controller

**Comment by acxz** [comment]
@liborw Created package repo [here](https://github.com/ros-noetic-arch/ros-noetic-joint-trajectory-controller)

Send a PR my view and I'll get it merged!

**Comment by acxz** [comment]
Due to inactivity I went ahead and created the PKGBUILD myself and push it out on the AUR.
