### ISSUE TITLE
Missing boost as dependecy

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-desktop-full#23]
There is some ROS package that missing boost as dependency. This is bad  because to quickly build ROS whenever boost is updated I use `yay -S $(pactree boost -r -l -d 1 | tail +2) --rebuild`.

**Comment by acxz** [comment]
This might be of interest: https://github.com/arch4edu/arch4edu/issues/78#issuecomment-673589824
