### ISSUE TITLE
Need to sync two AUR

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-desktop-full#24]
```
 -> ros-noetic-geographic-msgs: local (0.5.6-1) is newer than AUR (0.5.5-1)
 -> ros-noetic-robot-localization: local (2.7.2-1) is newer than AUR (2.7.1-1)
```
Would be nice if @acxz add me as co-maintainer of that two packages so I don;t need to bother this busy person every update.

**Comment by acxz** [comment]
Just added you as co-maintainer.

> bother this busy person every update

Haha, but seriously tho thanks for keeping up this, the community really needs people like you, I appreciate what you've done for this project this year.
