### ISSUE TITLE
Need AUR access

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-desktop-full#26]
Since log4cxx use smart pointer from 0.12.0, every ros noetic packaged that depends on ros-noetic-rosconsole need C++17 flag. I need access to https://aur.archlinux.org/packages/ros-noetic-pcl-ros and https://aur.archlinux.org/packages/ros-noetic-laser-filters to apply that patch.

**Comment by acxz** [comment]
Done!
