### ISSUE TITLE
Order in which to port packages

### ISSUE THREAD

**Issue by stertingen** [ros-noetic-arch/ros-noetic-desktop-full#3]
Using this script (https://gist.github.com/stertingen/ca18e1eb8cdfd53b67dd966be2300f48), I've found an order to port the ROS packages without running into dependency issues:

**ros**
https://github.com/ros-noetic-arch/ros-noetic-catkin
https://github.com/ros-noetic-arch/ros-noetic-cmake-modules
https://github.com/ros-noetic-arch/ros-noetic-cpp-common
https://github.com/ros-noetic-arch/ros-noetic-genmsg
https://github.com/ros-noetic-arch/ros-noetic-ros-environment
https://github.com/ros-noetic-arch/ros-noetic-rosboost-cfg
https://github.com/ros-noetic-arch/ros-noetic-rosclean
https://github.com/ros-noetic-arch/ros-noetic-rosmake
https://github.com/ros-noetic-arch/ros-noetic-gencpp
https://github.com/ros-noetic-arch/ros-noetic-geneus
https://github.com/ros-noetic-arch/ros-noetic-genlisp
https://github.com/ros-noetic-arch/ros-noetic-gennodejs
https://github.com/ros-noetic-arch/ros-noetic-genpy
https://github.com/ros-noetic-arch/ros-noetic-roslang
https://github.com/ros-noetic-arch/ros-noetic-rospack
https://github.com/ros-noetic-arch/ros-noetic-rostime
https://github.com/ros-noetic-arch/ros-noetic-message-generation
https://github.com/ros-noetic-arch/ros-noetic-rosbash
https://github.com/ros-noetic-arch/ros-noetic-roscpp-traits
https://github.com/ros-noetic-arch/ros-noetic-roslib
https://github.com/ros-noetic-arch/ros-noetic-roscpp-serialization
https://github.com/ros-noetic-arch/ros-noetic-roscreate
https://github.com/ros-noetic-arch/ros-noetic-rosunit
https://github.com/ros-noetic-arch/ros-noetic-message-runtime
https://github.com/ros-noetic-arch/ros-noetic-rosbuild
https://github.com/ros-noetic-arch/ros-noetic-mk
https://github.com/ros-noetic-arch/ros-noetic-ros

**ros_comm**
https://github.com/ros-noetic-arch/ros-noetic-rosgraph
https://github.com/ros-noetic-arch/ros-noetic-class-loader
https://github.com/ros-noetic-arch/ros-noetic-rosmaster
https://github.com/ros-noetic-arch/ros-noetic-rosparam
https://github.com/ros-noetic-arch/ros-noetic-xmlrpcpp
https://github.com/ros-noetic-arch/ros-noetic-roslz4
https://github.com/ros-noetic-arch/ros-noetic-std-msgs
https://github.com/ros-noetic-arch/ros-noetic-std-srvs
https://github.com/ros-noetic-arch/ros-noetic-rosconsole
https://github.com/ros-noetic-arch/ros-noetic-rosgraph-msgs
https://github.com/ros-noetic-arch/ros-noetic-pluginlib
https://github.com/ros-noetic-arch/ros-noetic-roscpp
https://github.com/ros-noetic-arch/ros-noetic-roslisp
https://github.com/ros-noetic-arch/ros-noetic-rosout
https://github.com/ros-noetic-arch/ros-noetic-rospy
https://github.com/ros-noetic-arch/ros-noetic-roslaunch
https://github.com/ros-noetic-arch/ros-noetic-rostest
https://github.com/ros-noetic-arch/ros-noetic-message-filters
https://github.com/ros-noetic-arch/ros-noetic-rosbag-storage
https://github.com/ros-noetic-arch/ros-noetic-topic-tools
https://github.com/ros-noetic-arch/ros-noetic-rosbag
https://github.com/ros-noetic-arch/ros-noetic-rosmsg
https://github.com/ros-noetic-arch/ros-noetic-rostopic
https://github.com/ros-noetic-arch/ros-noetic-rosnode
https://github.com/ros-noetic-arch/ros-noetic-rosservice
https://github.com/ros-noetic-arch/ros-noetic-roswtf
https://github.com/ros-noetic-arch/ros-noetic-ros-comm

**ros_core**
https://github.com/ros-noetic-arch/ros-noetic-rosbag-migration-rule
https://github.com/ros-noetic-arch/ros-noetic-roscpp-core
https://github.com/ros-noetic-arch/ros-noetic-actionlib-msgs
https://github.com/ros-noetic-arch/ros-noetic-diagnostic-msgs
https://github.com/ros-noetic-arch/ros-noetic-geometry-msgs
https://github.com/ros-noetic-arch/ros-noetic-nav-msgs
https://github.com/ros-noetic-arch/ros-noetic-rosconsole-bridge
https://github.com/ros-noetic-arch/ros-noetic-shape-msgs
https://github.com/ros-noetic-arch/ros-noetic-trajectory-msgs
https://github.com/ros-noetic-arch/ros-noetic-visualization-msgs
https://github.com/ros-noetic-arch/ros-noetic-sensor-msgs
https://github.com/ros-noetic-arch/ros-noetic-stereo-msgs
https://github.com/ros-noetic-arch/ros-noetic-common-msgs
https://github.com/ros-noetic-arch/ros-noetic-ros-core

**ros_base**
https://github.com/ros-noetic-arch/ros-noetic-smclib
https://github.com/ros-noetic-arch/ros-noetic-bond
https://github.com/ros-noetic-arch/ros-noetic-bondcpp
https://github.com/ros-noetic-arch/ros-noetic-bondpy
https://github.com/ros-noetic-arch/ros-noetic-nodelet
https://github.com/ros-noetic-arch/ros-noetic-bond-core
https://github.com/ros-noetic-arch/ros-noetic-actionlib
https://github.com/ros-noetic-arch/ros-noetic-dynamic-reconfigure
https://github.com/ros-noetic-arch/ros-noetic-nodelet-topic-tools
https://github.com/ros-noetic-arch/ros-noetic-nodelet-core
https://github.com/ros-noetic-arch/ros-noetic-ros-base

**robot**
https://github.com/ros-noetic-arch/ros-noetic-orocos-kdl
https://github.com/ros-noetic-arch/ros-noetic-roslint
https://github.com/ros-noetic-arch/ros-noetic-smach
https://github.com/ros-noetic-arch/ros-noetic-urdf-parser-plugin
https://github.com/ros-noetic-arch/ros-noetic-python-orocos-kdl
https://github.com/ros-noetic-arch/ros-noetic-angles
https://github.com/ros-noetic-arch/ros-noetic-smach-msgs
https://github.com/ros-noetic-arch/ros-noetic-eigen-conversions
https://github.com/ros-noetic-arch/ros-noetic-kdl-conversions
https://github.com/ros-noetic-arch/ros-noetic-tf2-msgs
https://github.com/ros-noetic-arch/ros-noetic-control-msgs
https://github.com/ros-noetic-arch/ros-noetic-tf2
https://github.com/ros-noetic-arch/ros-noetic-tf2-py
https://github.com/ros-noetic-arch/ros-noetic-urdfdom-py
https://github.com/ros-noetic-arch/ros-noetic-diagnostic-aggregator
https://github.com/ros-noetic-arch/ros-noetic-diagnostic-updater
https://github.com/ros-noetic-arch/ros-noetic-filters
https://github.com/ros-noetic-arch/ros-noetic-urdf
https://github.com/ros-noetic-arch/ros-noetic-xacro
https://github.com/ros-noetic-arch/ros-noetic-kdl-parser
https://github.com/ros-noetic-arch/ros-noetic-kdl-parser-py
https://github.com/ros-noetic-arch/ros-noetic-self-test
https://github.com/ros-noetic-arch/ros-noetic-diagnostic-analysis
https://github.com/ros-noetic-arch/ros-noetic-joint-state-publisher
https://github.com/ros-noetic-arch/ros-noetic-smach-ros
https://github.com/ros-noetic-arch/ros-noetic-tf2-ros
https://github.com/ros-noetic-arch/ros-noetic-executive-smach
https://github.com/ros-noetic-arch/ros-noetic-tf
https://github.com/ros-noetic-arch/ros-noetic-tf2-kdl
https://github.com/ros-noetic-arch/ros-noetic-diagnostic-common-diagnostics
https://github.com/ros-noetic-arch/ros-noetic-robot-state-publisher
https://github.com/ros-noetic-arch/ros-noetic-tf-conversions
https://github.com/ros-noetic-arch/ros-noetic-diagnostics
https://github.com/ros-noetic-arch/ros-noetic-geometry
https://github.com/ros-noetic-arch/ros-noetic-robot

**viz**
https://github.com/ros-noetic-arch/ros-noetic-gl-dependency
https://github.com/ros-noetic-arch/ros-noetic-media-export
https://github.com/ros-noetic-arch/ros-noetic-qwt-dependency
https://github.com/ros-noetic-arch/ros-noetic-webkit-dependency
https://github.com/ros-noetic-arch/ros-noetic-python-qt-binding
https://github.com/ros-noetic-arch/ros-noetic-qt-dotgraph
https://github.com/ros-noetic-arch/ros-noetic-qt-gui
https://github.com/ros-noetic-arch/ros-noetic-qt-gui-py-common
https://github.com/ros-noetic-arch/ros-noetic-resource-retriever
https://github.com/ros-noetic-arch/ros-noetic-qt-gui-cpp
https://github.com/ros-noetic-arch/ros-noetic-rqt-gui
https://github.com/ros-noetic-arch/ros-noetic-rqt-gui-py
https://github.com/ros-noetic-arch/ros-noetic-rqt-gui-cpp
https://github.com/ros-noetic-arch/ros-noetic-rqt-py-console
https://github.com/ros-noetic-arch/ros-noetic-rqt-runtime-monitor
https://github.com/ros-noetic-arch/ros-noetic-rqt-shell
https://github.com/ros-noetic-arch/ros-noetic-rqt-top
https://github.com/ros-noetic-arch/ros-noetic-rqt-web
https://github.com/ros-noetic-arch/ros-noetic-cv-bridge
https://github.com/ros-noetic-arch/ros-noetic-image-transport
https://github.com/ros-noetic-arch/ros-noetic-map-msgs
https://github.com/ros-noetic-arch/ros-noetic-rqt-robot-steering
https://github.com/ros-noetic-arch/ros-noetic-rqt-topic
https://github.com/ros-noetic-arch/ros-noetic-rqt-bag
https://github.com/ros-noetic-arch/ros-noetic-rqt-graph
https://github.com/ros-noetic-arch/ros-noetic-rqt-image-view
https://github.com/ros-noetic-arch/ros-noetic-rqt-logger-level
https://github.com/ros-noetic-arch/ros-noetic-rqt-dep
https://github.com/ros-noetic-arch/ros-noetic-rqt-py-common
https://github.com/ros-noetic-arch/ros-noetic-rqt-console
https://github.com/ros-noetic-arch/ros-noetic-rqt-moveit
https://github.com/ros-noetic-arch/ros-noetic-rqt-plot
https://github.com/ros-noetic-arch/ros-noetic-rqt-publisher
https://github.com/ros-noetic-arch/ros-noetic-rqt-robot-monitor
https://github.com/ros-noetic-arch/ros-noetic-rqt-service-caller
https://github.com/ros-noetic-arch/ros-noetic-rqt-tf-tree
https://github.com/ros-noetic-arch/ros-noetic-interactive-markers
https://github.com/ros-noetic-arch/ros-noetic-laser-geometry
https://github.com/ros-noetic-arch/ros-noetic-rqt-bag-plugins
https://github.com/ros-noetic-arch/ros-noetic-rqt-launch
https://github.com/ros-noetic-arch/ros-noetic-rqt-msg
https://github.com/ros-noetic-arch/ros-noetic-rqt-nav-view
https://github.com/ros-noetic-arch/ros-noetic-rqt-pose-view
https://github.com/ros-noetic-arch/ros-noetic-rqt-reconfigure
https://github.com/ros-noetic-arch/ros-noetic-rqt-action
https://github.com/ros-noetic-arch/ros-noetic-rqt-robot-dashboard
https://github.com/ros-noetic-arch/ros-noetic-rqt-srv
https://github.com/ros-noetic-arch/ros-noetic-rviz
https://github.com/ros-noetic-arch/ros-noetic-rqt-common-plugins
https://github.com/ros-noetic-arch/ros-noetic-rqt-rviz
https://github.com/ros-noetic-arch/ros-noetic-rqt-robot-plugins
https://github.com/ros-noetic-arch/ros-noetic-viz

**desktop**
https://github.com/ros-noetic-arch/ros-noetic-pluginlib-tutorials
https://github.com/ros-noetic-arch/ros-noetic-roscpp-tutorials
https://github.com/ros-noetic-arch/ros-noetic-turtlesim
https://github.com/ros-noetic-arch/ros-noetic-visualization-marker-tutorials
https://github.com/ros-noetic-arch/ros-noetic-nodelet-tutorial-math
https://github.com/ros-noetic-arch/ros-noetic-rospy-tutorials
https://github.com/ros-noetic-arch/ros-noetic-ros-tutorials
https://github.com/ros-noetic-arch/ros-noetic-actionlib-tutorials
https://github.com/ros-noetic-arch/ros-noetic-turtle-actionlib
https://github.com/ros-noetic-arch/ros-noetic-common-tutorials
https://github.com/ros-noetic-arch/ros-noetic-turtle-tf2
https://github.com/ros-noetic-arch/ros-noetic-turtle-tf
https://github.com/ros-noetic-arch/ros-noetic-geometry-tutorials
https://github.com/ros-noetic-arch/ros-noetic-interactive-marker-tutorials
https://github.com/ros-noetic-arch/ros-noetic-librviz-tutorial
https://github.com/ros-noetic-arch/ros-noetic-rviz-plugin-tutorials
https://github.com/ros-noetic-arch/ros-noetic-rviz-python-tutorial
https://github.com/ros-noetic-arch/ros-noetic-urdf-tutorial
https://github.com/ros-noetic-arch/ros-noetic-visualization-tutorials
https://github.com/ros-noetic-arch/ros-noetic-desktop

**perception**
https://github.com/ros-noetic-arch/ros-noetic-tf2-eigen
https://github.com/ros-noetic-arch/ros-noetic-camera-calibration-parsers
https://github.com/ros-noetic-arch/ros-noetic-image-geometry
https://github.com/ros-noetic-arch/ros-noetic-pcl-msgs
https://github.com/ros-noetic-arch/ros-noetic-camera-calibration
https://github.com/ros-noetic-arch/ros-noetic-camera-info-manager
https://github.com/ros-noetic-arch/ros-noetic-pcl-conversions
https://github.com/ros-noetic-arch/ros-noetic-polled-camera
https://github.com/ros-noetic-arch/ros-noetic-vision-opencv
https://github.com/ros-noetic-arch/ros-noetic-compressed-depth-image-transport
https://github.com/ros-noetic-arch/ros-noetic-compressed-image-transport
https://github.com/ros-noetic-arch/ros-noetic-image-common
https://github.com/ros-noetic-arch/ros-noetic-image-publisher
https://github.com/ros-noetic-arch/ros-noetic-image-view
https://github.com/ros-noetic-arch/ros-noetic-theora-image-transport
https://github.com/ros-noetic-arch/ros-noetic-depth-image-proc
https://github.com/ros-noetic-arch/ros-noetic-image-proc
https://github.com/ros-noetic-arch/ros-noetic-image-transport-plugins
https://github.com/ros-noetic-arch/ros-noetic-tf2-geometry-msgs
https://github.com/ros-noetic-arch/ros-noetic-image-rotate
https://github.com/ros-noetic-arch/ros-noetic-pcl-ros
https://github.com/ros-noetic-arch/ros-noetic-stereo-image-proc
https://github.com/ros-noetic-arch/ros-noetic-image-pipeline
https://github.com/ros-noetic-arch/ros-noetic-laser-assembler
https://github.com/ros-noetic-arch/ros-noetic-laser-filters
https://github.com/ros-noetic-arch/ros-noetic-perception-pcl
https://github.com/ros-noetic-arch/ros-noetic-laser-pipeline
https://github.com/ros-noetic-arch/ros-noetic-perception

**simulators**
https://github.com/ros-noetic-arch/ros-noetic-gazebo-dev
https://github.com/ros-noetic-arch/ros-noetic-stage
https://github.com/ros-noetic-arch/ros-noetic-gazebo-msgs
https://github.com/ros-noetic-arch/ros-noetic-gazebo-ros
https://github.com/ros-noetic-arch/ros-noetic-stage-ros
https://github.com/ros-noetic-arch/ros-noetic-gazebo-plugins
https://github.com/ros-noetic-arch/ros-noetic-gazebo-ros-pkgs
https://github.com/ros-noetic-arch/ros-noetic-simulators

**desktop_full**
https://github.com/ros-noetic-arch/ros-noetic-hardware-interface
https://github.com/ros-noetic-arch/ros-noetic-controller-interface
https://github.com/ros-noetic-arch/ros-noetic-transmission-interface
https://github.com/ros-noetic-arch/ros-noetic-joint-limits-interface
https://github.com/ros-noetic-arch/ros-noetic-controller-manager-msgs
https://github.com/ros-noetic-arch/ros-noetic-controller-manager
https://github.com/ros-noetic-arch/ros-noetic-realtime-tools
https://github.com/ros-noetic-arch/ros-noetic-control-toolbox
https://github.com/ros-noetic-arch/ros-noetic-forward-command-controller
https://github.com/ros-noetic-arch/ros-noetic-joint-state-controller
https://github.com/ros-noetic-arch/ros-noetic-diff-drive-controller
https://github.com/ros-noetic-arch/ros-noetic-position-controllers
https://github.com/ros-noetic-arch/ros-noetic-gazebo-ros-control
https://github.com/ros-noetic-arch/ros-noetic-urdf-sim-tutorial
https://github.com/ros-noetic-arch/ros-noetic-desktop-full

**Comment by acxz** [comment]
All packages have been synced and thus I am closing this issue.
