### ISSUE TITLE
Unflag already up-to-date package

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-desktop-full#36]
Hi @acxz, please unflag https://aur.archlinux.org/packages/ros-noetic-robot-localization and https://aur.archlinux.org/packages/ros-noetic-geographic-msgs. Someone flagged them because they think the newest version is for ROS1. I just learned that co-maintainer cannot unflag pakage.

**Comment by acxz** [comment]
Yep was taking care of them right now. Do you mind sending @carlosal1015 an email (and CC me) to stop doing this? This is not the first time he has done it nor only for ROS packages. He just goes around and flags packages even if he doesn't use them. It is very disrespectful behavior.

**Comment by AchmadFathoni** [comment]
I've emailed him some explanation.
