### ISSUE TITLE
Not able  to install with newest poco 1.12.4-1

### ISSUE THREAD

**Issue by LumenYoung** [ros-noetic-arch/ros-noetic-desktop-full#43]
Hi, dear maintainer of the ros-noetic-arch. As suggested in the title. Some of the packages in `ros-noetic-desktop-full` relies on the `/usr/lib/libPocoFoundation.so.91`. Which is removed with the newest poco version in arch repository.

Reproduce: try to install `ros-noetic-desktop-full` on archlinux.

Expected behavior: successfully installed

Actual behavior: the installation fails due to `libPocoFoundation.so.91` not found.

Also, this problem also happens when I try to install `ros-noetic-turtlebot3` meta package.

Thank you for your effort to make ros noetic available for arch users.

**Comment by AchmadFathoni** [comment]
You can try install ros-noetic via conda environment [here](https://robostack.github.io/GettingStarted.html)

**Comment by acxz** [comment]
The current suggested solution is the following: https://github.com/ros-noetic-arch/ros-noetic-desktop-full/issues/10#issuecomment-653168991
